### ISSUE TITLE
ActionController::UnpermittedParameters - found unpermitted parameters: commentable_type, commentable_id

### ISSUE THREAD

**Issue by dept42** [the-teacher/the_comments#34]
I was receiving this error, with a fresh install of 2.2.2 on rails 4.1.5:

```
ActionController::UnpermittedParameters - found unpermitted parameters: commentable_type, commentable_id:
  actionpack (4.1.5) lib/action_controller/metal/strong_parameters.rb:377:in `unpermitted_parameters!'
  actionpack (4.1.5) lib/action_controller/metal/strong_parameters.rb:270:in `permit'
  the_comments (2.2.2) app/controllers/concerns/controller.rb:168:in `comment_params'
  the_comments (2.2.2) app/controllers/concerns/controller.rb:113:in `create'
```

I was able to easily fix by adding this to my own comments_controller:

```ruby
  def comment_params
    params
    .require(:comment)
    .permit(:title, :contacts, :raw_content, :parent_id, :commentable_type, :commentable_id)
    .merge(denormalized_fields)
    .merge(request_data_for_comment)
    .merge(tolerance_time: params[:tolerance_time].to_i)
    .merge(user: current_user, view_token: comments_view_token)
  end
```

..but I don't understand how it ever could have worked by default. Is this a bug, or is something wrong with my installation?

**Comment by alexpchin** [comment]
In the view, have you edited @post
```
<%= render partial: 'the_comments/tree', locals: { commentable: @post, comments_tree: @comments } %>
```
?

**Comment by the-teacher** [comment]
btw: secret project: https://github.com/TheComments

**Comment by the-teacher** [comment]
out of date. sorry
